// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1-eb93yN5725gSy59caY3izCa56EmuSE',
    appId: '1:871659401627:web:36174229449eadb112f13e',
    messagingSenderId: '871659401627',
    projectId: 'zenora-9802f',
    authDomain: 'zenora-9802f.firebaseapp.com',
    databaseURL: 'https://zenora-9802f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'zenora-9802f.firebasestorage.app',
    measurementId: 'G-E8BMK9NTQ7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4j0tL3UBS1hIXXiAoCLIyEOab4Ln-sHc',
    appId: '1:871659401627:android:06cdbb00b9fdd4b812f13e',
    messagingSenderId: '871659401627',
    projectId: 'zenora-9802f',
    databaseURL: 'https://zenora-9802f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'zenora-9802f.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1-eb93yN5725gSy59caY3izCa56EmuSE',
    appId: '1:871659401627:web:63eae5130d58804e12f13e',
    messagingSenderId: '871659401627',
    projectId: 'zenora-9802f',
    authDomain: 'zenora-9802f.firebaseapp.com',
    databaseURL: 'https://zenora-9802f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'zenora-9802f.firebasestorage.app',
    measurementId: 'G-YS302Z4V4R',
  );
}
